### ISSUE TITLE
[error]Unhandled: fatal: bad revision

### ISSUE THREAD

**Issue by raphaelmoreira** [ewellnitz/pr-inspection-assistant#28]
Hi!

I trying your extension and I don´t know what I´m doing wrong:

# Azure AI Foundry | Azure OpenAI Service
**Model**: gpt-4 (version:turbo-2024-04-09)

# YML

```yml
trigger: none

jobs:
  - job: BuildAndReview
    displayName: 'Build e Code Review'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        persistCredentials: true

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: DotNetCoreCLI@2
        displayName: 'Restore dependências'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build da aplicação'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration Release'

      - task: PRIA@2
        displayName: 'Code Review com Open AI'
        inputs:
          api_key: 'my-key' 
          api_version: 'turbo-2024-04-09'
          api_endpoint: 'https://my-instance.openai.azure.com/'
          ai_model: 'gpt-4'
```

# My change (C#)

![Image](https://github.com/user-attachments/assets/3cfe0b3b-748c-43b7-bfa6-1a20e11a640a)

# Result

```txt
GetDiff()  -- Scalar4Net/Controllers/RepoController.cs
##[error]Unhandled: fatal: bad revision ''

##[error]Error: fatal: bad revision ''

    at Object.action (/home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:1451:25)
    at PluginStore.exec (/home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:1500:29)
    at /home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:1927:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:1925:16)
    at GitExecutorChain.<anonymous> (/home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:1909:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/PRIA_d3b07384-d9a7-4f3b-8a1d-6e5f3d2b5c3a/2.1.26/node_modules/simple-git/dist/cjs/index.js:52:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

[fulllog.txt](https://github.com/user-attachments/files/20927160/fulllog.txt)
